require 'bioinform/data_models/positional_matrix'
require 'bioinform/data_models/positional_count_matrix'
require 'bioinform/data_models/positional_weight_matrix'
require 'bioinform/data_models/positional_probability_matrix'
#require 'bioinform/data_models/iupac_word'
#require 'bioinform/data_models/iupac'  #require 'bioinform/data_models/iupac_vocabulary'