require 'bioinform/data_models/pm'
require 'bioinform/data_models/pcm'
require 'bioinform/data_models/pwm'
require 'bioinform/data_models/ppm'
#require 'bioinform/data_models/iupac_word'
#require 'bioinform/data_models/iupac_wordset'